In [4]:
from scipy.optimize import fsolve
import numpy as np

In [26]:
x = np.array([2, 3, 5, 6, 2, 2])
y = np.array([3, 2, 1, 4, 4, 2])

In [36]:
# z = [ z1, z2, z3, z4, z5, z6]
z = x - y

def func(z):
    return [np.sqrt(sum(z**2))-5, 0, 0, 0, 0, 0]

roots = fsolve(func, z)

x - roots

array([2., 2., 1., 4., 4., 2.])

In [28]:
roots

array([-3.91849723e-09,  1.00000000e+00,  4.00000000e+00,  2.00000000e+00,
       -2.00000000e+00,  0.00000000e+00])

In [29]:
x-roots

array([2., 2., 1., 4., 4., 2.])

In [30]:
y= np.array([2., 2., 1., 4., 4., 2.])

In [32]:
print(x,y)

[2 3 5 6 2 2] [2. 2. 1. 4. 4. 2.]


In [33]:
x-y

array([ 0.,  1.,  4.,  2., -2.,  0.])

In [35]:
sum((x-y)**2)

25.0

In [12]:
np.sqrt(sum((roots)**2))

5.0

In [ ]:
# Alternative solution
>>> def f(x):
...     return x[0]*14.80461 + x[1]*(-4.9233) + x[2]*(10*0.4803) 
>>> def vf(x):
...    return [f(x), 0, 0]
>> xx = fsolve(vf, x0=[0,0,1])
>>> 
>>> f(xx)
8.8817841970012523e-16

In [14]:
# Another solution
import numpy as np
import scipy.optimize as opt

x = np.array([2, 3, 5, 6, 2, 2])
y = np.array([1, 1, 1, 1, 1, 1])

def func(y):
    x = np.array([2, 3, 5, 6, 2, 2])
    z = np.sqrt(np.sum((x-y)**2)) - 5
    return  np.zeros(x.shape[0],) + z

r = opt.root(func, x0=y, method='hybr')
print(r.x)
# array([1.51287563, 2.93792864, 2.41974376, 1.82313836, 1.49719936, 1.36584456])

print(np.sqrt(np.sum((x-r.x)**2)))
# 5.0

[1.51287563 2.93792864 2.41974376 1.82313836 1.49719936 1.36584456]
5.0


array([0.48712437, 0.06207136, 2.58025624, 4.17686164, 0.50280064,
       0.63415544])

25.00000003500858

5.000000003500858